<project>
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.cavetale.pom</groupId>
    <artifactId>cavetale-pom-base</artifactId>
    <version>0.1-SNAPSHOT</version>
  </parent>

  <groupId>com.cavetale.chair</groupId>
  <artifactId>chair</artifactId>
  <version>0.1-SNAPSHOT</version>

  <name>Chair</name>
  <url>https://github.com/StarTux/Chair</url>
  <packaging>jar</packaging>

  <dependencies>

    <!-- Paper API -->
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Lombok -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>

  </dependencies>
</project>
