main: com.cavetale.chair.ChairPlugin

name: Chair
version: 0.1
api-version: '1.21.11'

description: Use stairs as chairs
author: StarTux
website: https://cavetale.com

depend: []
softdepend: []

permissions:
  chair.use:
    description: Sit in chairs
    default: op
